package net.tigereye.chestcavity

import net.neoforged.neoforge.common.ModConfigSpec

object CCConfig {
    private val BUILDER = ModConfigSpec.Builder()

    // Core
    val ORGAN_BUNDLE_LOOTING_BOOST = BUILDER.comment("Looting boost per level for organ drops")
        .defineInRange("core.organ_bundle_looting_boost", 0.01, 0.0, 1.0)
    val UNIVERSAL_DONOR_RATE = BUILDER.comment("Chance of organs being universal donor")
        .defineInRange("core.universal_donor_rate", 0.025, 0.0, 1.0)
    val ORGAN_REJECTION_DAMAGE = BUILDER.comment("Damage dealt by organ rejection")
        .defineInRange("core.organ_rejection_damage", 2, 0, 100)
    val ORGAN_REJECTION_RATE = BUILDER.comment("Base ticks between organ rejection checks")
        .defineInRange("core.organ_rejection_rate", 600, 1, 72000)
    val HEARTBLEED_RATE = BUILDER.comment("Ticks between heartbleed damage")
        .defineInRange("core.heartbleed_rate", 20, 1, 72000)
    val KIDNEY_RATE = BUILDER.comment("Ticks between kidney filtration")
        .defineInRange("core.kidney_rate", 60, 1, 72000)
    val FILTRATION_DURATION_FACTOR = BUILDER.comment("Kidney poison duration reduction factor")
        .defineInRange("core.filtration_duration_factor", 1.0, 0.0, 10.0)
    val APPENDIX_LUCK = BUILDER.comment("Luck bonus per appendix")
        .defineInRange("core.appendix_luck", 0.1, 0.0, 10.0)
    val HEART_HP = BUILDER.comment("Health per heart organ")
        .defineInRange("core.heart_hp", 4.0, 0.0, 100.0)
    val MUSCLE_STRENGTH = BUILDER.comment("Attack damage from 8 stacks of muscles")
        .defineInRange("core.muscle_strength", 1.0, 0.0, 100.0)
    val MUSCLE_SPEED = BUILDER.comment("Movement speed from 8 stacks of muscles")
        .defineInRange("core.muscle_speed", 0.5, 0.0, 10.0)
    val NERVES_HASTE = BUILDER.comment("Mining/attack speed per spine")
        .defineInRange("core.nerves_haste", 0.1, 0.0, 10.0)
    val BONE_DEFENSE = BUILDER.comment("Damage reduction from 4 stacks of ribs")
        .defineInRange("core.bone_defense", 0.5, 0.0, 1.0)
    val RISK_OF_PRIONS = BUILDER.comment("Chance of prion disease from human meat")
        .defineInRange("core.risk_of_prions", 0.01, 0.0, 1.0)
    val CHEST_OPENER_ABSOLUTE_HEALTH_THRESHOLD = BUILDER.comment("HP below which chest can be opened")
        .defineInRange("core.chest_opener_absolute_health_threshold", 20, 0, 1000)
    val CHEST_OPENER_FRACTIONAL_HEALTH_THRESHOLD = BUILDER.comment("Fraction of max HP below which chest can be opened")
        .defineInRange("core.chest_opener_fractional_health_threshold", 0.5, 0.0, 1.0)
    val CAN_OPEN_OTHER_PLAYERS = BUILDER.comment("Allow opening other players' chests")
        .define("core.can_open_other_players", false)
    val KEEP_CHEST_CAVITY = BUILDER.comment("Keep chest cavity contents on death")
        .define("core.keep_chest_cavity", false)
    val DISABLE_ORGAN_REJECTION = BUILDER.comment("Disable organ rejection entirely")
        .define("core.disable_organ_rejection", false)

    // Ability tuning
    val ARROW_DODGE_DISTANCE = BUILDER.comment("Max teleport distance for arrow dodging")
        .defineInRange("abilities.arrow_dodge_distance", 32, 1, 128)
    val BUFF_PURGING_DURATION_FACTOR = BUILDER.comment("Wither duration reduction from withered bones")
        .defineInRange("abilities.buff_purging_duration_factor", 0.5, 0.0, 1.0)
    val CRYSTALSYNTHESIS_RANGE = BUILDER.comment("End crystal link range")
        .defineInRange("abilities.crystalsynthesis_range", 32, 1, 128)
    val CRYSTALSYNTHESIS_FREQUENCY = BUILDER.comment("Ticks between crystal link updates")
        .defineInRange("abilities.crystalsynthesis_frequency", 10, 1, 200)
    val FIREPROOF_DEFENSE = BUILDER.comment("Fire damage reduction from fireproof organs")
        .defineInRange("abilities.fireproof_defense", 0.75, 0.0, 1.0)
    val IMPACT_DEFENSE = BUILDER.comment("Impact damage reduction")
        .defineInRange("abilities.impact_defense", 0.75, 0.0, 1.0)
    val IRON_REPAIR_PERCENT = BUILDER.comment("Health restored by iron repair")
        .defineInRange("abilities.iron_repair_percent", 0.25, 0.0, 1.0)
    val LAUNCHING_POWER = BUILDER.comment("Upward velocity per launching score")
        .defineInRange("abilities.launching_power", 0.1, 0.0, 10.0)
    val MAX_TELEPORT_ATTEMPTS = BUILDER.comment("Max attempts to find teleport destination")
        .defineInRange("abilities.max_teleport_attempts", 5, 1, 100)
    val PHOTOSYNTHESIS_FREQUENCY = BUILDER.comment("Ticks for 8 photosynthetic organs to restore 1 hunger")
        .defineInRange("abilities.photosynthesis_frequency", 50, 1, 6000)
    val RUMINATION_TIME = BUILDER.comment("Ticks to eat a unit of grass")
        .defineInRange("abilities.rumination_time", 400, 1, 6000)
    val RUMINATION_GRASS_PER_SQUARE = BUILDER.comment("Grass units per block")
        .defineInRange("abilities.rumination_grass_per_square", 2, 1, 64)
    val RUMINATION_SQUARES_PER_STOMACH = BUILDER.comment("Grass blocks a stomach can hold")
        .defineInRange("abilities.rumination_squares_per_stomach", 3, 1, 64)
    val SHULKER_BULLET_TARGETING_RANGE = BUILDER.comment("Shulker bullet targeting range")
        .defineInRange("abilities.shulker_bullet_targeting_range", 20, 1, 128)
    val SWIMSPEED_FACTOR = BUILDER.comment("Swim speed boost from 8 swimming muscles")
        .defineInRange("abilities.swimspeed_factor", 1.0, 0.0, 10.0)
    val WITHERED_DURATION_FACTOR = BUILDER.comment("Wither duration factor from withered bones")
        .defineInRange("abilities.withered_duration_factor", 0.5, 0.0, 1.0)

    // Cooldowns
    val ARROW_DODGE_COOLDOWN = BUILDER.defineInRange("cooldowns.arrow_dodge", 200, 1, 72000)
    val DRAGON_BOMB_COOLDOWN = BUILDER.defineInRange("cooldowns.dragon_bomb", 200, 1, 72000)
    val DRAGON_BREATH_COOLDOWN = BUILDER.defineInRange("cooldowns.dragon_breath", 200, 1, 72000)
    val EXPLOSION_COOLDOWN = BUILDER.defineInRange("cooldowns.explosion", 200, 1, 72000)
    val FORCEFUL_SPIT_COOLDOWN = BUILDER.defineInRange("cooldowns.forceful_spit", 20, 1, 72000)
    val GHASTLY_COOLDOWN = BUILDER.defineInRange("cooldowns.ghastly", 60, 1, 72000)
    val IRON_REPAIR_COOLDOWN = BUILDER.defineInRange("cooldowns.iron_repair", 1200, 1, 72000)
    val PYROMANCY_COOLDOWN = BUILDER.defineInRange("cooldowns.pyromancy", 78, 1, 72000)
    val SHULKER_BULLET_COOLDOWN = BUILDER.defineInRange("cooldowns.shulker_bullet", 100, 1, 72000)
    val SILK_COOLDOWN = BUILDER.defineInRange("cooldowns.silk", 20, 1, 72000)
    val VENOM_COOLDOWN = BUILDER.defineInRange("cooldowns.venom", 40, 1, 72000)

    val SPEC: ModConfigSpec = BUILDER.build()
}
